# PHP 中的异常处理

> 原文：<https://www.javatpoint.com/exception-handling-in-php>

异常处理是 PHP 的一个强大机制，用于处理运行时错误(运行时错误称为异常)。从而可以维持应用程序的正常流程。

使用异常处理的主要目的是**维护应用**的正常执行。

## 什么是例外？

异常是程序未被接受的结果，可以由程序自己处理。基本上，异常会扰乱程序的正常流程。但是它不同于错误，因为异常可以被处理，而错误不能被程序本身处理。

换句话说，——“程序的意外结果是异常，可以由程序本身处理。”PHP 中可以抛出和捕捉异常。

## 为什么需要异常处理？

PHP 提供了一个强大的机制，异常处理。它允许您处理运行时错误，如 IOException、SQLException、ClassNotFoundException 等。异常处理最常见的例子是-除以零异常，这是一种算术异常。

#### 注意:当异常中断程序或应用程序的正常执行时，需要异常处理。

异常处理在所有编程语言中几乎都是相似的。当出现指定的错误情况时，它会改变程序的正常流程，这种情况称为异常。为此，PHP 提供了以下关键词:

**试试-**

try 块包含可能有异常或可能出现异常的代码。当一个异常在代码运行时出现在 try 块中时，它会被捕获并在 catch 块中被解析。try 块后面必须跟有 catch 或 finally 块。一个尝试块后面可以跟随最小一个和最大任意数量的捕获块。

**catch -**

catch 块包含在引发指定异常时执行的代码。它总是与 try block 一起使用，而不是单独使用。当异常发生时，PHP 会找到匹配的 catch 块。

**投掷-**

这是一个用于引发异常的关键字。它还有助于列出一个函数抛出但自己不处理的所有异常。

请记住，每次投掷必须至少有一个“接球”。

**最后-**

finally 块包含一个代码，用于 PHP 中的清理活动。基本上，它执行程序的基本代码。

## 当异常被触发时会发生什么-

*   保存代码的当前状态。
*   代码的执行被切换到预定义的异常处理函数。
*   根据情况，处理程序可以暂停程序的执行，从保存的代码状态恢复执行，或者从代码中的另一个位置继续执行代码。

## 异常处理相对于错误处理的优势

异常处理是 PHP 中的一个重要机制，它比错误处理有以下优势-

**错误类型分组-**

在 PHP 中，基本对象和对象都可以作为异常抛出。它可以创建异常对象的层次结构，并在类中对异常进行分组，还可以根据它们的类型对它们进行分类。

**保持错误处理和正常代码分开-**

在传统的错误处理中，if-else 块用于处理错误。它使代码不可读，因为处理错误和条件的代码混合在一起了。在 try-catch 块中，异常与代码保持分离，代码变得可读。

## 例子

借助示例了解异常处理在 PHP 中是如何工作的-

**例 1**

让我们举一个例子来解释抛投和试接球拦网的常见流程:

```php
<?php
//user-defined function with an exception
function checkNumber($num) {
   if($num>=1) {
     //throw an exception
     throw new Exception("Value must be less than 1");
   }
   return true;
}

//trigger an exception in a "try" block
try {
   checkNumber(5);
   //If the exception throws, below text will not be display
   echo 'If you see this text, the passed value is less than 1';
}

//catch exception
catch (Exception $e) {
   echo 'Exception Message: ' .$e->getMessage();
}
?>

```

**输出:**

```php
Exception Message: Value must be less than 1

```

**示例 2:创建自定义异常**

您可以通过扩展异常类来创建用户定义的异常。查看下面的代码，了解如何创建用户定义的异常-

```php
<?php
class DivideByZeroException extends Exception { }
class DivideByNegativeNoException extends Exception { }
function checkdivisor($dividend, $divisor){
    // Throw exception if divisor is zero
  try {
      if ($divisor == 0) {
        throw new DivideByZeroException;
      } 
      else if ($divisor < 0) {
         throw new DivideByNegativeNoException; 
      } 
      else {
        $result = $dividend / $divisor;
        echo "Result of division = $result </br>";
      }
    }
    catch (DivideByZeroException $dze) {
        echo "Divide by Zero Exception! </br>";
    }
    catch (DivideByNegativeNoException $dnne) {
        echo "Divide by Negative Number Exception </br>";
    }
    catch (Exception $ex) {
        echo "Unknown Exception";
    }
}

    checkdivisor(18, 3);
    checkdivisor(34, -6);
    checkdivisor(27, 0);
?>

```

**输出:**

```php
Result of division = 6
Divide by Zero Exception!
Divide by Negative Number Exception!

```

要详细了解试捕块，[点击此处](php-try-catch)。

* * *