# PHP 试捕

> 原文:[https://www.javatpoint.com/php-try-catch](https://www.javatpoint.com/php-try-catch)

PHP try 和 catch 是具有异常处理功能的块，其中包含处理异常的代码。它们在异常处理中起着重要的作用。试抓块还有一个比较重要的关键词是**扔**。**抛出**是一个用来抛出异常的关键词。

每个尝试块必须至少有一个 catch 块。另一方面，一个 try 块也可以有多个 catch 块来处理各种异常类。

### 句法

异常处理中使用以下语法来处理运行时错误-

```
<?php
            //try block
	try {
		//code that can throw exception
	} 
            //catch block
catch (Exception $e) {
		//code to print exception caught in the block
	}
	//finally block
	finally {
		//any code that will always execute 
}
?>

```

让我们更详细地了解试投接球:

### 尝试

try 块包含可能包含异常的代码。运行时在 try 块中引发的异常被 catch 块捕获。因此，每个 try 块必须至少有一个 catch 块。它由可能发生异常的代码块组成。

关于尝试，需要注意以下几点:

*   try 块后面必须跟一个 catch 或 finally 块。
*   一个 try 块必须至少有一个 catch 块。
*   一个试块可以有多个 catch 块。

### 捕捉

catch 块捕获在 try 块中引发的异常。它包含捕获异常的代码，该异常是由 try 块中的 throw 关键字引发的。抛出特定异常时，catch 块执行。PHP 查找匹配的 catch 块，并将异常对象分配给一个变量。

关于捕获，需要注意以下几点:

*   一次尝试可以有多个捕捉块。
*   引发的异常由一个或多个 catch 捕获并解决。
*   catch 块总是与 try 块一起使用。它不能单独使用。
*   它就在试块之后。

### 扔

它是一个关键字，用于引发异常。注意一次投掷至少有一个“**抓**块”来抓异常。

它列出了函数引发的异常，这些异常不能由函数本身处理。

### 最后

它是一个包含要执行的程序的**基本代码**的块。最后一个块也用于 PHP 中的清理活动。它类似于 catch 块，用于处理异常。唯一的区别是，无论是否处理异常，它总是执行。

可以在 catch 块之后或代替 catch 块指定 finally 块。无论是否抛出异常，它总是在 try 和 catch 块之后，正常执行重新开始之前执行。它在以下场景中很有用- **关闭数据库连接**、**流**。

### 例 1

让我们举一个例子来解释投掷和试接球以及最后拦网的常见流程:

```
<?php
//user-defined function with an exception
function checkNumber($num) {
   if($num>=1) {
     //throw an exception
     throw new Exception("Value must be less than 1");
   }
   return true;
}

//trigger an exception in a "try" block
try {
   checkNumber(5);
   //If the exception throws, below text will not be display
   echo 'If you see this text, the passed value is less than 1';
}

//catch exception
catch (Exception $e) {
   echo 'Exception Message: ' .$e->getMessage();
}
finally {
   echo '</br> It is finally block, which always executes.';
}
?>

```

**输出:**

```
Exception Message: Value must be less than 1
It is finally block, which always executes.

```

### 例 2

```
<?php

//user-defined function with an exception
function testEven($num) {
    //trigger an exception in a "try" block
    try {
         if($num%2 == 1) {
           //throw an exception
           throw new Exception("Passed number is an ODD Number");
           echo "After throw this statement will not execute";
          }
          echo '</br> <b> If you see this text, the passed value is an EVEN Number </b>';
     }
     //catch exception
     catch (Exception $e) {
         echo '</br> <b> Exception Message: ' .$e->getMessage() .'</b>';
     }
     finally {
        echo '</br> It is finally block, which always executes.';
     }
}
      echo 'Output for ODD Number';
      testEven(19);

      echo '</br> </br>';
      echo 'Output for EVEN Number';
     testEven(12);

?>

```

**输出:**

在下面的输出中，您可以看到当一个奇数被传递时，会显示一条异常消息。另一方面，当传递一个偶数时，会显示另一条消息。

```
Output for ODD Number 
Exception Message: Passed number is an ODD Number
It is finally block, which always executes.

Output for EVEN Number
If you see this text, the passed value is an EVEN Number
It is finally block, which always executes.

```

### 示例 2:自定义异常和多重捕获语句

在下面的示例中，我们将创建一个扩展异常类的自定义异常类。这里，我们还将使用多个 catch 块和一个 try 块。

```
<?php
class OddNumberException extends Exception { }
//user-defined function with an exception
function testEven($num) {
    //trigger an exception in a "try" block
    try {
         if($num%2 == 1) {
           //throw an exception
           throw new OddNumberException;
           echo "After throw this statement will not execute";
          }
          echo '</br> <b> If you see this text, the passed value is an EVEN Number </b>';
     }

     //catch exception
     catch (OddNumberException $ex) {
         echo '</br> <b> Exception Message: ODD Number' .'</b>';
     }
     //catch exception
     catch (Exception $e) {
         echo '</br> <b> Exception Message: ' .$e->getMessage() .'</b>';
     }

}
   echo 'Output for EVEN Number';
   testEven(28);
   echo '</br> </br>';
   echo 'Output for ODD Number';
   testEven(17);
?>

```

**输出:**

```
Output for EVEN Number
If you see this text, the passed value is an EVEN Number 

Output for ODD Number 
Exception Message: ODD Number

```

**要点:**

*   除了 PHP 异常类及其子类，我们还可以创建自己的自定义异常类来处理非匹配异常。
*   在 PHP 5.5 及以上版本中，finally block 用于处理异常。无论是否抛出异常，这个块总是被执行。

* * *